### ISSUE TITLE
Does not work for every format

### ISSUE THREAD

**Issue by guillaumebriday-pa** [mateus4k/currency-to-float#1]
when input does not have decimal, it fails to parse

```js
parse('$123,456,789') => NaN
```

Any idea how to fix that?

**Comment by mateus4k** [comment]
Hi! 👋
I will look at how to solve this problem. 
I'll update you soon!

**Comment by guillaumebriday-pa** [comment]
I tried some workaround but unfortunately without a little bit of context, I'm afraid there is not a lot we can do about it.

Most of libraries ask the input format as option but sometime we don't know it.

**Comment by mateus4k** [comment]
Try to update the package now:
```bash
npm update currency-to-float
```
It's on v1.2.3 now! :slightly_smiling_face:
