### ISSUE TITLE
'MODULE_NOT_FOUND'

### ISSUE THREAD

**Issue by jlssmt** [mateus4k/currency-to-float#3]
Hey,

after my PR and merge today, the module isn't working anymore.
The lib folder in node_modules is missing.

Before (v1.2.3):
![image](https://user-images.githubusercontent.com/42897917/151244223-8024a530-025c-46fc-a63a-60d9e4930b9a.png)

After (v1.2.4):
![image](https://user-images.githubusercontent.com/42897917/151244255-44fc89a0-ee06-4f66-bd86-b58ad53e3270.png)

**Comment by mateus4k** [comment]
Sorry, it was my mistake. Please test again with 1.2.5

**Comment by jlssmt** [comment]
works. thanks.
