### ISSUE TITLE
Can't import properly into TS project

### ISSUE THREAD

**Issue by jlssmt** [mateus4k/currency-to-float#4]
Another problem for me.
I can't import it properly into my TypeScript project. There are missing types.
I tried to fix it for my own and pull request the solution, but I didn't get it working. 
So maybe you know how to fix it?

```
error TS7016: Could not find a declaration file for module 'currency-to-float'. '~pathToMyProject~/node_modules/currency-to-float/lib/esm/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/currency-to-float` if it exists or add a new declaration (.d.ts) file containing `declare module 'currency-to-float';`
```

**Comment by jlssmt** [comment]
maybe it's a missing "typings" property in package.json

https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam#answer-41307319

**Comment by mateus4k** [comment]
I believe it has been fixed. I added generation of type declaration files. Could you try again with version 1.3.1?
```sh
npm i currency-to-float@^1.3
```

**Comment by jlssmt** [comment]
works. ty
