### ISSUE TITLE
Parse incorrectly handles strings with place separators but without decimals 

### ISSUE THREAD

**Issue by src-code** [mateus4k/currency-to-float#5]
The following test case fails for `parse()`, as it treats the comma as a decimal marker and returns a float:

```js
const parse = require('currency-to-float').parse;
console.log(parse('$1,234')); // returns 1.234
```

**Comment by src-code** [comment]
I see something similar was addressed in v1.2.3 but doesn't seem to be correct in v1.3.1

https://github.com/mateus4k/currency-to-float/issues/1

**Comment by mateus4k** [comment]
Hi! I'll take a look at this case 🙂

**Comment by mateus4k** [comment]
Hey! Are you expecting the int `1234` after parsing?

**Comment by src-code** [comment]
> Are you expecting the int 1234 after parsing?

@mateus4k Yes, that's correct!

**Comment by mateus4k** [comment]
@src-code in this case you must add a decimal case to work well. It's necessary to make this works for all currencies at the same time without having to pass any options parameter :slightly_smiling_face: 

```ts
const value = '$1,234';
console.log(parse(`${value},00`)); //1234
```

**Comment by src-code** [comment]
@mateus4k Perhaps this could be done by the library - if the value isn't a valid `Number` (eg, contains a places separator somewhere) simply check the 3rd-to-last char and if it's a comma or period, you know you have a decimal portion already.  If one is not found, append it before parsing, using the appropriate type (if comma was previously found as places separator, use a period, etc.)

**Comment by mateus4k** [comment]
@src-code I'm not sure looking at the third-to-last digit would be a good idea, since then the values would be limited to two decimal places. Can you open a pull request with your suggestions? We can think of using a flag through the second parameter to enable this :thinking:
